# Generated by Django 3.1.6 on 2021-05-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name': 'Cryptocurrency', 'verbose_name_plural': 'Cryptocurrencies'},
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='full_info_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.IntegerField(help_text='CoinMarketCap ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(help_text='Cryptocurrency Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(help_text='Cryptocurrency Symbol', max_length=10),
        ),
    ]
