# Generated by Django 3.1.6 on 2021-05-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210507_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(help_text='Cryptocurrency Symbol', max_length=50),
        ),
    ]
