# Generated by Django 3.1.6 on 2021-05-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20210507_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['-market_cap'], 'verbose_name': 'Cryptocurrency', 'verbose_name_plural': 'Cryptocurrencies'},
        ),
    ]
