# Generated by Django 3.1.6 on 2021-05-11 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20210507_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='platform_symbol',
            field=models.CharField(blank=True, default='', help_text='Parent platform symbol', max_length=50),
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='platform_token_address',
            field=models.CharField(blank=True, default='', help_text='Parent platform toke address', max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
