# Generated by Django 3.1.6 on 2021-05-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20210511_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='manually_added',
            field=models.BooleanField(default=False),
        ),
    ]
