# Generated by Django 3.1.6 on 2021-05-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_cryptocurrency_manually_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourchanThreadsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('last_checked', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialScraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FOURCHAN', '4chan'), ('TWITTER', 'Twitter'), ('REDDIT', 'Reddit')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CryptocurrencySocialMentions',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('created_at', models.PositiveBigIntegerField()),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='scraper.cryptocurrency')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scraper.socialscraper')),
            ],
        ),
    ]
