# Generated by Django 3.1.6 on 2021-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_auto_20210513_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourchanthreadsstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='fourchanthreadsstatus',
            name='thread_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
