# Generated by Django 3.1.6 on 2021-05-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20210513_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrencysocialmentions',
            options={'verbose_name': 'Cryptocurrency Social Mention', 'verbose_name_plural': 'Cryptocurrency Social Mentions'},
        ),
        migrations.AlterModelOptions(
            name='fourchanthreadsstatus',
            options={'verbose_name': '4chan Thread Status', 'verbose_name_plural': '4chan Threads Statuses'},
        ),
        migrations.AlterModelOptions(
            name='socialscraper',
            options={'verbose_name': 'Social Scraper', 'verbose_name_plural': 'Social Scrapers'},
        ),
        migrations.AddField(
            model_name='cryptocurrencysocialmentions',
            name='post_id',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptocurrencysocialmentions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fourchanthreadsstatus',
            name='last_checked',
            field=models.DateTimeField(help_text='Date and time when thread posts when read last time'),
        ),
        migrations.AlterField(
            model_name='fourchanthreadsstatus',
            name='thread_id',
            field=models.IntegerField(help_text='4chan thread ID', primary_key=True, serialize=False),
        ),
    ]
