# Generated by Django 3.1.6 on 2021-05-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_symbolblacklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolblacklistitem',
            name='cryptocurrency',
            field=models.OneToOneField(help_text='Associated cryptocurrency', on_delete=django.db.models.deletion.CASCADE, related_name='blacklist', to='scraper.cryptocurrency'),
        ),
    ]
