# Generated by Django 3.1.6 on 2021-05-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_auto_20210518_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTrackedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(help_text='Account username. Eg. @twitter', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether account is active and will be used to search.')),
                ('last_checked_tweet_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
