# Generated by Django 3.1.6 on 2021-05-19 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_twittertrackedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twittertrackedaccount',
            name='last_checked_tweet_id',
        ),
        migrations.AddField(
            model_name='twittertrackedaccount',
            name='last_checked',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 21, 53, 0, 364719, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twittertrackedaccount',
            name='twitter_username',
            field=models.CharField(help_text='Account username. Eg. twitter', max_length=15),
        ),
    ]
