# Generated by Django 3.1.6 on 2021-06-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_auto_20210520_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditTrackedCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(help_text='Community username.', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether community is active and will be used to search.')),
                ('last_checked', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Reddit Tracked Community',
                'verbose_name_plural': 'Reddit Tracked Communities',
            },
        ),
    ]
