# Generated by Django 3.2 on 2022-09-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210701_1906'),
        ('scraper', '0015_reddittrackedcommunity'),
    ]

    operations = [
    ]
