# Generated by Django 3.1 on 2022-11-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_auto_20221115_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='positive_sentiment_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='today_trend',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='yesterday_trend',
        ),
    ]
