# Generated by Django 3.1 on 2022-11-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0019_auto_20221115_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEnrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.IntegerField()),
                ('positive_sentiment_percent', models.IntegerField(default=0)),
                ('yesterday_trend', models.IntegerField(default=0)),
                ('today_trend', models.IntegerField(default=0)),
            ],
        ),
    ]
