# Generated by Django 3.1 on 2022-11-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0020_dataenrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataenrichment',
            name='scraper_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
