# Generated by Django 3.1 on 2022-11-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0021_dataenrichment_scraper_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataenrichment',
            unique_together={('currency_id', 'scraper_id')},
        ),
    ]
