# Generated by Django 3.1 on 2022-11-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_auto_20221115_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataenrichment',
            unique_together=set(),
        ),
    ]
