# Generated by Django 3.1 on 2022-11-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0023_auto_20221115_1840'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataenrichment',
            unique_together={('currency_id', 'scraper_id')},
        ),
    ]
