# Generated by Django 3.1 on 2022-11-17 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0025_auto_20221115_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrencyreport',
            name='last_enriched',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
