# Generated by Django 3.1 on 2022-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0026_cryptocurrencyreport_last_enriched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencyreport',
            name='positive_sentiment_percent',
            field=models.FloatField(default=0),
        ),
    ]
