# Generated by Django 3.2 on 2023-01-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0028_dataenrichment_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataenrichment',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', help_text='Cryptocurrency Name', max_length=50),
        ),
    ]
