# Generated by Django 4.1.5 on 2023-01-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_dataenrichment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataenrichment',
            name='currency_id',
            field=models.IntegerField(unique=True),
        ),
    ]
