# Generated by Django 4.1.5 on 2023-01-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0030_alter_dataenrichment_currency_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataenrichment',
            old_name='scraper_id',
            new_name='scraper_id_enrichment',
        ),
        migrations.AlterUniqueTogether(
            name='dataenrichment',
            unique_together={('currency_id', 'scraper_id_enrichment')},
        ),
    ]
