# Generated by Django 4.1.5 on 2023-01-25 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0031_rename_scraper_id_dataenrichment_scraper_id_enrichment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='last_enriched',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='positive_sentiment_percent',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='today_trend',
        ),
        migrations.RemoveField(
            model_name='cryptocurrencyreport',
            name='yesterday_trend',
        ),
    ]
