# Generated by Django 4.1.5 on 2023-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0032_remove_cryptocurrencyreport_last_enriched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrencyreport',
            name='platform_type',
            field=models.CharField(blank=True, default='', help_text='Parent platform token type eth etc', max_length=100),
        ),
    ]
